x11()

talog_bins=read.csv("./talog/niceplots/talog_bins.csv")
plot(talog_bins$minu, talog_bins$meas*100, xlab="Minutes",ylab="Matric potential, cm water")
lines(talog_bins$minu, talog_bins$hundr*100,col="RED",lwd=3)
lines(talog_bins$minu, talog_bins$thous*100,col="BLUE",lwd=3)
legend(1000,-80,c("Measured","100 bins","1000 bins"),pch=c(1,-1,-1),lty=c(0,1,1),lwd=c(1,2.5,2.5),col=c('black','red','blue'))
locator(1)

par(mfrow=c(2,1))
talog_pond=read.csv("./talog/niceplots/ponding.csv")
plot(talog_pond$minu, type="n", xlab="Minutes", ylab="Ponding depth, cm water",ylim=c(0,20),xlim=c(0,1440))
lines(talog_pond$minu,talog_pond$noposur*100,col="RED",lwd=3)
lines(talog_pond$minu, talog_pond$posur*100,col="BLUE",lwd=3)
legend(800,10,c("Modeled (w/ estimated Ksat)","Modeled (w/ measured Ksat)"),pch=c(1,-1,-1),lty=c(0,1,1),lwd=c(1,2.5,2.5),col=c('black','red','blue'))
plot(talog_pond$minu, talog_bins$meas*100, xlab="Minutes",ylab="Matric potential, cm water")
lines(talog_pond$minu, talog_bins$hundr*100,col="RED",lwd=3)
lines(talog_pond$minu, rep(mean(talog_bins$meas[1:5]),96)*100,col="BLUE",lwd=3)
legend(800,-80,c("Measured","Modeled (estimated Ksat)","Modeled (measured Ksat)"),pch=c(1,-1,-1),lty=c(0,1,1),lwd=c(1,2.5,2.5),col=c('black','red','blue'))
locator(1)
